# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

    env(ETRAXIS_LOCALE): en

    env(LDAP_URL):    ~
    env(LDAP_BASEDN): ~

    env(OAUTH_GOOGLE_CLIENT_ID):     ~
    env(OAUTH_GOOGLE_CLIENT_SECRET): ~

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Dictionary/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Message/'
            - '../src/Tests/'

    App\MessageHandler\:
        resource: '../src/MessageHandler/'
        autoconfigure: false

    _instanceof:
        App\MessageBus\Contracts\CommandHandlerInterface:
            tags: [{ name: messenger.message_handler, bus: command.bus }]
        App\MessageBus\Contracts\QueryHandlerInterface:
            tags: [{ name: messenger.message_handler, bus: query.bus }]
        App\MessageBus\Contracts\EventHandlerInterface:
            tags: [{ name: messenger.message_handler, bus: event.bus }]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\DataFixtures\ProductionFixtures:
        $locale: '%env(ETRAXIS_LOCALE)%'

    App\EventListener\StickyLocale:
        $locale: '%env(ETRAXIS_LOCALE)%'

    App\MessageHandler\Users\RegisterExternalAccountCommandHandler:
        $locale: '%env(ETRAXIS_LOCALE)%'

    App\Security\LDAP\LdapService:
        $url:    '%env(LDAP_URL)%'
        $basedn: '%env(LDAP_BASEDN)%'
